# Generated by Django 4.2 on 2023-12-01 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('activos', '0002_alter_activos_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=16, unique=True)),
                ('simcard', models.PositiveIntegerField(null=True)),
                ('operador', models.CharField(max_length=50, null=True)),
                ('activo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_activo_set', to='activos.activos')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_cliente_set', to='clientes.clientes')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
