# Generated by Django 4.2 on 2023-12-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos',
            name='placa',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
